### ISSUE TITLE
Public users cannot list VPNPeers objects

### ISSUE THREAD

**Issue by junekiwi** [EdgeNet-project/edgenet-legacy-2024#156]
```
panic: vpnpeers.networking.edgenet.io is forbidden: User "system:serviceaccount:registration:public-user" cannot list resource "vpnpeers" in API group "networking.edgenet.io" at the cluster scope
```

**Comment by bsenel** [comment]
I see what the issue is! [b60762e](https://github.com/EdgeNet-project/edgenet/commit/b60762e7be4646f9509b70fbc5a80e51fc8a669a) allows to get and list VPN Peers as the public user and by anonymous calls.

We shall remove the old cluster roles and bindings with their service accounts, such as `system:serviceaccount:registration:public-user`, after the holidays from the production cluster.

I am closing this issue.

**Comment by junekiwi** [comment]
I forgot about it, but public users should also be able to create VPNPeer objects :-)

```
vpnpeers.networking.edgenet.io is forbidden: User "system:serviceaccount:registration:public-user" cannot create resource "vpnpeers" in API group "networking.edgenet.io" at the cluster scope
```

**Comment by junekiwi** [comment]
All good, thanks @bsenel!
