### ISSUE TITLE
Sync system time

### ISSUE THREAD

**Issue by boldt** [EdgeNet-project/edgenet-legacy-2024#56]
Please ensure, that the system time is synced between all nodes in the cluster.

For example, there is an offset of 5-6 minutes between **missouri.edge-net.io** and **kansas.edge-net.io**.
Like this, it is impossible to work with a distibuted logging, e.g., match send and receive packages.

**Comment by aaaaalbert** [comment]
Can you run an NTP client in your pods for this? (The pod's time is usually the system's, which we don't always control in our deployment.)

**Comment by boldt** [comment]
Your suggestion means, I have to add an NTP client to every pod, e.g., every container, e.g., every image.

Thus, it is not possible to use standard docker containers out of the box. It means, for every standard container I must derive my own image which includes the NTP client.

Isn't there any other way?

**Comment by aaaaalbert** [comment]
Perhaps the images you are using already contain an NTP client. Then it's (approximately) one additional line of config in the pod YAML to start it.

Whether a centralized/platform implementation of this feature is possible, I cannot say for sure yet. I suggested the pod-based approach because *you are in control* then, and you aren't blocked on our progress.
